#include "../../pch.h"

#include "../../Constants.h"

TEST(LogLevel, LogLevelToInt) {
	ASSERT_EQ(TIE::LogLevel::COMMAND, TIE::COMMAND_INT_VALUE);
	ASSERT_EQ(TIE::LogLevel::ERROR, TIE::ERROR_INT_VALUE);
	ASSERT_EQ(TIE::LogLevel::WARN, TIE::WARN_INT_VALUE);
	ASSERT_EQ(TIE::LogLevel::INFO, TIE::INFO_INT_VALUE);
	ASSERT_EQ(TIE::LogLevel::DEBUG, TIE::DEBUG_INT_VALUE);
}

TEST(LogLevel, StringToLogLevel) {
	ASSERT_EQ(TIE::LogLevel::COMMAND, TIE::strToLogLevel(TIE::COMMAND_STRING_VALUE_UC));
	ASSERT_EQ(TIE::LogLevel::ERROR, TIE::strToLogLevel(TIE::ERROR_STRING_VALUE_UC));
	ASSERT_EQ(TIE::LogLevel::WARN, TIE::strToLogLevel(TIE::WARN_STRING_VALUE_UC));
	ASSERT_EQ(TIE::LogLevel::INFO, TIE::strToLogLevel(TIE::INFO_STRING_VALUE_UC));
	ASSERT_EQ(TIE::LogLevel::DEBUG, TIE::strToLogLevel(TIE::DEBUG_STRING_VALUE_UC));

	ASSERT_EQ(TIE::LogLevel::COMMAND, TIE::strToLogLevel(TIE::COMMAND_STRING_VALUE_LC));
	ASSERT_EQ(TIE::LogLevel::ERROR, TIE::strToLogLevel(TIE::ERROR_STRING_VALUE_LC));
	ASSERT_EQ(TIE::LogLevel::WARN, TIE::strToLogLevel(TIE::WARN_STRING_VALUE_LC));
	ASSERT_EQ(TIE::LogLevel::INFO, TIE::strToLogLevel(TIE::INFO_STRING_VALUE_LC));
	ASSERT_EQ(TIE::LogLevel::DEBUG, TIE::strToLogLevel(TIE::DEBUG_STRING_VALUE_LC));
}

TEST(LogLevel, LogLevelHeirarchy) {
	ASSERT_GE(TIE::LogLevel::DEBUG, TIE::LogLevel::INFO);
	ASSERT_GE(TIE::LogLevel::INFO, TIE::LogLevel::WARN);
	ASSERT_GE(TIE::LogLevel::WARN, TIE::LogLevel::ERROR);
	ASSERT_GE(TIE::LogLevel::ERROR, TIE::LogLevel::COMMAND);
}