#ifndef TEXTALIGNMENT_H
#define TEXTALIGNMENT_H

namespace TIE {

	enum class TextAlignment {
		TOP_RIGHT, TOP_CENTER, TOP_LEFT, 
		CENTER_LEFT, CENTER, CENTER_RIGHT,
		BOTTOM_RIGHT, BOTTOM_CENTER, BOTTOM_LEFT
	};

}

#endif
